apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-app
spec:
  selector:
    matchLabels:
      app: fruit-app
  replicas: 3
  template:
    metadata:
      labels:
        app: fruit-app
    spec:
     containers:
     - name: fruit-app
       image: docker.io/sepenoo84/fruit-app:latest
       ports:
       - containerPort: 8080