apiVersion: v1
kind: Service
metadata:
  name: fruit-app
spec:
  selector:
    app: fruit-app
  type: NodePort
  ports:
  - name: fruit-app
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30004